export default function Forums() {
  return (
    <>
      <div>
        this is where all topics will be. 

        <h1>Topics are for navigating / organizing discussions. These are generated by Nokl, for both general topics and game ids</h1>
      </div>
    </>
      
  );
}